egs/hkust/asr/v1/run.sh
=> Revert "Update run.sh"

docs/tutorials/emotion_class_example.md
#24
[TODO] You can assign the pull request to reviewers by mentioning(@) their usernames.
=> add emotion tutorial

delta/data/task/speaker_cls_task.py, delta/models/speaker_cls_rawmodel.py, egs/voxceleb/spk/v1/run_delta.sh, tools/test.sh
refactor voxceleb egs 
egs/voxceleb/spk/v1/run_delta.sh
N/A
=> fix voxceleb

delta/utils/cmvn_test.py
Fix #29 
Add unit test for apply_local_cmvn.
python delta/utils/cmvn_test.py
@zh794390558
=> Add unit test for apply_local_cmvn.

delta/utils/loss/base_loss.py, delta/utils/loss/loss_impl.py, delta/utils/loss/loss_utils.py, delta/utils/loss/loss_utils_test.py
Fix #39 
[TODO] add focal loss . #39 
[TODO] python loss_utils_test.py
[TODO] @zh794390558
=> add focal loss

egs/voxceleb/spk/v1/README.md, egs/voxceleb/spk/v1/conf/tdnn_arcface.yml, egs/voxceleb/spk/v1/run_delta.sh
Fix speaker on voxceleb readme.
`pushd egs/voxceleb/spk/v1 && bash run_delta.sh`
N/A
=> fix spaker readme

.github/pull_request_template.md
Fix pull request template
N/A
N/A
=> fix pull request template [skip ci]

tools/Makefile, tools/install/install-deltann.sh
Fix #44 
cd delta/tools && ./install/intall-deltann.sh
@zh794390558
=> fix install-deltann

tools/Makefile
fix mbedtls install for deltann
`pushd tools/install && install-deltann.sh`
=> fix mbedtls install

docs/development/contributing.md
=> add golang style docs

docs/installation/deltann_compile.md
Fix  tensorflow and deltann build.
N/A
=> fix deltann_compile.md

docs/installation/manual_setup.md
Add cudnn support version.
N/A
=> fix cuda support doc

docs/installation/manual_setup.md
=> fix cuda install

docs/installation/manual_setup.md
https://github.com/tensorflow/tensorflow/issues/31249
reference:
https://github.com/tensorflow/tensorflow/issues/6968
N/A
=> Fix Install doc

delta/utils/solver/utils/solver_utils.py, egs/iemocap/emo/v1/README.md, egs/voxceleb/spk/v1/README.md
more info for egs doc
remove duplicate interface.
N/A
=> fix dup and doc

delta/models/speaker_cls_rawmodel.py, delta/utils/solver/speaker_solver.py, egs/voxceleb/spk/v1/conf/tdnn_arcface.yml, egs/voxceleb/spk/v1/conf/tdnn_softmax.yml
remove some useless config field, and fix config
pushd egs/voxceleb/spk/v1 && run_delta.sh
=> remove vocab from speaker

.github/stale.yml, delta/data/task/speaker_cls_task.py, delta/data/task/speaker_cls_task_test.py, delta/layers/common_layers.py, delta/layers/ops/kernels/delta_delta.cc, delta/layers/ops/kernels/fbank_op.cc, delta/layers/ops/kernels/x_ops.cc, delta/models/asr_model.py, delta/models/speaker_cls_rawmodel.py, delta/utils/cmvn_test.py, delta/utils/loss/loss_impl.py, delta/utils/loss/loss_utils.py, delta/utils/loss/loss_utils_test.py, delta/utils/metrics/tf_metrics.py, delta/utils/optimizer/yellowfin.py, delta/utils/solver/speaker_solver.py, deltann/api/c_api.h, deltann/core/graph.cc, deltann/core/io.h, deltann/core/runtime.h, deltann/core/utils/config.cc, deltann/core/utils/misc.h, egs/hkust/asr/v1/conf/fbank.conf, egs/hkust/asr/v1/run.sh, egs/voxceleb/spk/v1/conf/tdnn_arcface.yml, egs/voxceleb/spk/v1/conf/tdnn_softmax.yml, egs/voxceleb/spk/v1/run_delta.sh, tools/Makefile
fix speaker_rawmodel for resnet
fix pip install
add stale robot
update hkust egs
formt code
pushd egs/voxceleb/spk/v1 && bash run_delta.sh
=> fix spk model for resnet, mix update and fix

README.md, delta/models/asr_model.py, egs/hkust/asr/v1/README.md, egs/hkust/asr/v1/conf/asr-ctc.yml, egs/iemocap/emo/v1/README.md
Update doc and config.
Goto egs and test.
=> Fix egs doc

delta/utils/solver/raw_solver.py
fix customer model path config error
fix #80 
set customer model path in config file when infer
=> fix solver config

delta/utils/loss/loss_impl.py, delta/utils/loss/loss_utils.py, delta/utils/loss/loss_utils_test.py
[TODO]  add alpha for focal loss. Fix #73
=> add alpha for focal loss

delta/layers/common_layers.py, delta/layers/common_layers_test.py, delta/utils/metrics/tf_metrics_test.py, delta/utils/postprocess/speaker_cls_proc.py, egs/voxceleb/spk/v1/conf/tdnn_arcface.yml, egs/voxceleb/spk/v1/conf/tdnn_softmax.yml
refactor speaker outputs
Goto egs/voxceleb to run run_delta.sh.
=> Spk postproc

egs/hkust/asr/v1/README.md
=> fix hkust results

docs/version.md
add version no. specification.
No
=> add version doc

README.md, delta/data/task/speech_cls_task.py, egs/iemocap/emo/v1/README.md, egs/iemocap/emo/v1/conf/emo-keras-blstm.yml
fix iemocap config and results.
No
=> fix emotion results

delta/utils/loss/loss_utils_test.py, delta/utils/misc.py, delta/utils/solver/estimator_solver.py, deltann/api/c_api.cc, deltann/api/c_api.h, deltann/core/graph.cc, deltann/core/runtime.h, deltann/core/tfmodel.cc, deltann/core/tfserving_model.h, deltann/examples/text_cls/test.cc, deltann/test/test.cc
Fix #66 
goto voxceleb egs and run_delta.sh.
=> fix metrics for binary class

delta/serving/eval_asr_pb.py, delta/utils/solver/utils/solver_utils.py, delta/utils/solver/utils/solver_utils_test.py
[TODO] Add Asr restore model test case
#50 
[TODO] python delta/utils/solver/utils/solver_utils_test.py
=> Asr restore model testcase

egs/hkust/asr/v1/local/hkust_prepare_dict.sh
=> fix hkust prepare dict

delta/serving/eval_asr_pb.py, delta/utils/solver/asr_solver.py, delta/utils/solver/estimator_solver.py, delta/utils/solver/utils/solver_utils.py, delta/utils/solver/utils/solver_utils_test.py, deltann/core/runtime.h, utils/speech/ctc_token_fst.py, utils/speech/prep_ctc_trans.py
fix estimator train hook log.
no label log when training with estimator.
=> Fix train hook

docs/installation/using_docker.md
=> modify document:docker start command

deltann/core/data.h
Fix variable length input.
run `deltann/example/text_cls`
=> fix for variable len input

delta/utils/misc.py
=> fix distribute

docs/tutorials/training/speech_features.md
=> add speech feature doc

delta/compat.py, delta/compat_test.py
using `import delta.compat as tf` for tf1.x 
`import tensorflow as tf` for 2.x
unit test pass
=> add compat for tf1.x [skip ci]

delta/data/preprocess/base_preparer.py, delta/data/utils/common_utils.py
update error information about length check in prepare_raw_data()
tested
=> fix len check

.gitignore, deltann/server/examples/build.sh, deltann/server/examples/run.sh, deltann/server/examples/server-env.sh, deltann/server/mock_yaml/nlp/model.yaml, dpl/run.sh, tools/install/install-go.sh
- fix deltann build shell
- fix dpl build shell
None
=> fix build shell

deltann/Makefile, deltann/api/c_api.cc, deltann/core/base_model.h, deltann/core/buffer.h, deltann/core/config.cc, deltann/core/config.h, deltann/core/data.h, deltann/core/graph.cc, deltann/core/graph.h, deltann/core/io.h, deltann/core/logging.h, deltann/core/misc.cc, deltann/core/misc.h, deltann/core/runtime.h, deltann/core/shape.cc, deltann/core/tflite_model.h, deltann/core/tfmodel.h, deltann/core/utils/https.h, deltann/core/utils/https_client.h, deltann/examples/text_cls/test.cc, deltann/targets/linux_makefile.inc
move config misc from utils to core
test passing.
=> refactor deltann utils 

delta/serving/eval_speech_cls_pb.py, delta/utils/postprocess/speaker_cls_proc.py
add speaker python serving code
passed.
=> add spk serving

README.md
Update readme for installation guide.
See preview https://github.com/didi/delta/tree/update-install-readme
=> Update readme for installation

docs/installation/wheel_build.md
Update doc for wheel building.
=> Modifiy wheel build doc

deltann/server/README.md, deltann/server/examples/build.sh, deltann/server/examples/server-env.sh
- fix deltann serving build shell
- fix README
None
=> *fix build sh & README

deltann/server/examples/Dockerfile, deltann/server/examples/build.sh, deltann/server/examples/run.sh
- deltann serving add docker support
None
=> *add docker support

docs/development/deltann_compile.md
=> fix deltann doc

tools/release_notes.py
=> *add release_notes

utils/avg_checkpoints.py
=> fix avg ckpt

tools/release_notes.py
- add Acknowledgements
- fix bug
None
=> *add Acknowledgements

tools/Makefile
=> defualt kaldi build with openblas

egs/conll2003/pretrain/v1/local/modeling.py, egs/conll2003/pretrain/v1/local/tokenization.py, egs/conll2003/pretrain/v1/local/transfer_bert_model.py, egs/conll2003/pretrain/v1/run_bert.sh
Current BERT usage is not compatible with TF2.0. This PR changes some files for TF2.0 compatibility.
Besides some delta files are changed, because the script will download BERT code files, I also modified two BERT files for TF2.0 compatibility and overwrite the original files: `modeling.py` and `tokenization.py`. The original version can be found here: https://github.com/google-research/bert/blob/master/tokenization.py and https://github.com/google-research/bert/blob/master/modeling.py. The diff can be found here: https://gist.github.com/hankun11/4ca9d6e850ffdc5c3c0fd4698ea9b898/revisions and https://gist.github.com/hankun11/f938eea514b11476b090184577ee6825/revisions
`delta --cmd …
=> Bert for tf2.0

README.md, docs/development/docker.md
add more info for deltann compile
none
=> add more info for deltann compile

tools/Makefile
fix pip install option
ci pass
=> add --no-cache-dir for pip

delta/utils/solver/emotion_solver.py
fix keras emotion bugs
egs/iemocap/emo/v1/run.sh train and eval work well.
=> fix kerase emotion base class

delta/utils/solver/utils/solver_utils.py
fix keras solver utils bugs
test pass
=> fix solver utils bugs

docs/version.md, tools/release_notes.py
=> add release version doc

deltann/infer/CMakeLists.txt
add delta infer CMakeLists.txt
=> add delta infer CMakeLists.txt

deltann/infer/cmake/tensorflow.cmake, deltann/infer/cmake/utils.cmake, deltann/infer/delta_infer/CMakeLists.txt, deltann/infer/python/CMakeLists.txt
=> Delta infer

.gitignore, core/ops/build.sh, dpl/run.sh, tools/Makefile
fix deltann compile and depends.
=> deltann compile

core/ops/kernels/jieba_op.cc, core/ops/kernels/simple_vocab_op.cc, core/ops/kernels/string_utils_op.cc, core/ops/kernels/tokenizer_ops.cc, deltann/core/io.h, deltann/core/tfmodel.cc, deltann/core/tfmodel.h, deltann/targets/linux_makefile.inc, dpl/run.sh
=> replace string to tstring for >= 2.2.0 and missing symbol of MakeShape and Status

deltann/api/c_api.cc, deltann/api/c_api.h, deltann/core/io.h, deltann/core/runtime.cc, deltann/core/runtime.h, deltann/core/shape.cc, deltann/core/shape.h, deltann/core/tfmodel.cc, deltann/examples/speaker/test.cc, deltann/examples/text_cls/model.yaml, deltann/examples/text_cls/test.cc, deltann/test/test.cc
=> replace deltann inoutData size by nelms

env.sh, tools/requirements.txt
=> fix delta with tf2.2.0

delta/utils/misc.py, delta/utils/model.py, delta/utils/solver/estimator_solver.py, deltann/api/c_api.cc, deltann/core/buffer.h, deltann/core/io.h, deltann/core/runtime.cc, deltann/core/runtime.h, deltann/core/tfmodel.cc, deltann/examples/speaker/test.cc, deltann/infer/delta_infer/core/scatter_search.cc, deltann/infer/delta_infer/custom_ops/platform/CUDA/transformer_functor_cu.cc, deltann/infer/delta_infer/custom_ops/transformer_cell.cc, deltann/infer/delta_infer/custom_ops/transformer_cell_bert.cc, deltann/infer/delta_infer/custom_ops/transformer_cell_nlp.cc, deltann/infer/python/delta_infer/cpp/delta_cpp_export_py.cc, deltann/infer/python/delta_infer/optimizer.py, egs/voxceleb/spk/v1/conf/tdnn_arcface.yml, egs/voxceleb/spk/v1/conf/tdnn_softmax.yml
https://github.com/google-research/bert/blob/master/run_pretraining.py#L154
init from checkpoint
=> Transfer learning

tools/release_notes.py
=> dump release note to markdown

delta/data/preprocess/utils.py
[TODO] amend embedded matrix by deleting linalg.norm and changing bound for unk in delta/data/preprocess/utils.py
=> delete linalg.norm and amend bound

core/ops/kernels/delta_delta.cc, core/ops/kernels/delta_delta.h, core/ops/kernels/fbank.cc, core/ops/kernels/fbank.h, core/ops/kernels/mel_spectrum.cc, core/ops/kernels/mel_spectrum.h, core/ops/kernels/mel_spectrum_op.cc, core/ops/kernels/pitch.cc, core/ops/kernels/pitch.h, core/ops/kernels/pitch_op.cc, core/ops/kernels/spectrum.cc, core/ops/kernels/x_ops.cc, core/ops/py_x_ops.py, delta/data/frontend/fbank.py, delta/data/frontend/fbank_pitch.py, delta/data/frontend/fbank_test.py, delta/data/frontend/mel_spectrum.py, delta/data/frontend/mel_spectrum_test.py, delta/data/frontend/mfcc.py, delta/data/frontend/pitch.py, delta/data/frontend/pitch_test.py, delta/data/frontend/spectrum.py
=> Update ops of speech features

core/ops/build.sh, deltann/server/core/conf/delta_conf.go, deltann/server/core/delta_serving.go, deltann/server/core/model/delta_model.go, deltann/server/core/types/delta_types.go, deltann/server/mock_yaml/nlp/model.yaml, tools/install/install-go.sh
fix deltann serving valueInputs
None
=> *fix valueInputs

deltann/api/c_api.cc, deltann/api/c_api.h, deltann/core/runtime.cc, deltann/examples/text_cls/model.yaml, deltann/examples/text_conf_json/Makefile, deltann/examples/text_conf_json/model.yaml, deltann/examples/text_conf_json/test_conf_json.cc
=> deltann parse json inputs

RELEASE.md
=> Add release md
